POST http://localhost:3000/api/employee/login
Content-Type: application/json

{
    "username" : "username",
    "password" : "123456"
}

###
GET http://localhost:3000/api/user/60aafc9415c42638d0bb4bb1
Content-Type: application/json

{
}

###
POST http://localhost:3000/api/employee/add
Content-Type: application/json

{
    "username" : "username",
    "password" : "123456",
    "repassword" : "123456",
    "fullname" : "tran long an",
    "phonenumber" : "012345678",
    "work": "cleck",
    "dateofbirth": "10/05/2000",
    "mailaddress": "cleck@gmail.com",
    "salary": 2000000
}

###
PUT  http://localhost:3000/api/user/60ab09d26cca0820580a6fd7
Content-Type: application/json

{
    "username" : "username123",
    "password" : "123456789",
    "fullname" : "tran long an 123",
    "phonenumber" : "01234567812",
    "dateofbirth" : "10/05/2000"
}
